name: ttv-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - langchain>=0.1.0
      - langchain-google-genai>=0.0.5
      - openai-whisper>=20231117
      - elevenlabs>=0.3.0
      - moviepy>=1.0.3
      - python-dotenv>=0.19.0
      - pathlib>=1.0.1
      - requests>=2.31.0
      - typing>=3.7.4
      - typing-extensions>=4.5.0